name: http_resource
version: 0.1.1
description: >-
  This library allows you to simple map your models into crud objects that will automatically update it's values.
author: Michał Poreda <michal.poreda94@gmail.com>
# homepage: https://example-pet-store.com/newtify
# documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: ^0.12.0
dev_dependencies:
